"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {supabase} from "../lib/supabase";
import MarkdownContent from "./MarkdownContent";
import PublicHeader from "./PublicHeader";
import PublicFooter from "./PublicFooter";
type Kind="articles"|"projects";type Row=Record<string,string|null>;
const fallback:Record<string,Row>={
 "resilient-transitions-toolkit":{title_lt:"Resilient Transitions Toolkit",summary_lt:"Nemokamas praktinis koučingo ir improvizacijos įrankių rinkinys jaunimo darbuotojams ir mokytojams, padedantiems jauniems žmonėms atrasti kitą žingsnį.",description_lt:"## Įrankių rinkinys jau paruoštas — ir jis nemokamas\n\n2026 m. liepą 18 jaunimo darbuotojų ir mokytojų iš Slovėnijos, Turkijos, Serbijos, Lietuvos ir Šiaurės Makedonijos aštuonias dienas praleido Maribore. Jie mokėsi, kaip koučingas ir improvizacija gali padėti jauniems žmonėms, kurie jaučiasi įstrigę: neturi darbo, nemato aiškaus kito žingsnio ar stokoja pasitikėjimo savimi.\n\n## Kas pateko į leidinį\n\n- 20 pratimų, jungiančių į sprendimus orientuotą koučingą ir improvizaciją\n- 3 paruošti užsiėmimų planai: nedirbančiam ir nesimokančiam jaunimui, mokyklą ar karjerą besirenkantiems mokiniams ir verslo idėją išbandantiems jaunuoliams\n- Aiškūs žingsniai, trukmės ir aptarimo klausimai, kad metodus galėtumėte iškart naudoti kitame užsiėmime\n\nLeidinys parengtas anglų kalba. Jį galima nemokamai atsisiųsti, dalytis ir adaptuoti pagal **CC BY-SA 4.0** licenciją.\n\n[📥 Atsisiųsti „Resilient Transitions Toolkit“](https://entreact.eu/Resilient_Transitions_Toolkit_EN)\n\n[🌐 Daugiau apie „EntreAct“ projektą](https://entreact.eu)\n\nJei dirbate su jaunimu, išbandykite šiuos metodus ir pasidalykite patirtimi su kolegomis, kuriems jie gali būti naudingi.\n\n> Projektą bendrai finansuoja Europos Sąjunga. Išreikštos nuomonės ir požiūriai yra tik autoriaus (-ių) ir nebūtinai atspindi Europos Sąjungos ar Nacionalinės agentūros MOVIT poziciją. Nei Europos Sąjunga, nei finansavimą teikianti institucija negali būti už juos atsakingos.",project_year:"2026",programme:"Erasmus+ · EntreAct",project_code:"EntreAct",image_url:"/projects/resilient-transitions-toolkit.jpg"},
 "create-edit-employ":{title_lt:"Create, Edit, Employ",summary_lt:"Vaizdo kūrimo įgūdžiai geresnei profesinei ateičiai.",description_lt:"Šis Erasmus+ projektas padeda jauniems žmonėms praktiškai išmokti kurti, redaguoti ir tikslingai naudoti vaizdo turinį. Dalyviai stiprina skaitmeninį pasitikėjimą, kūrybiškumą ir profesinį pasirengimą.",project_year:"2025",programme:"Erasmus+ KA153",project_code:"2025-1-LT02-KA153-YOU-000305541"},
 "making-the-right-career-choices":{title_lt:"Making the Right Career Choices",summary_lt:"Sąmoningi ir informuoti jaunimo karjeros pasirinkimai.",description_lt:"Projektas suteikia jaunuoliams erdvę pažinti savo stiprybes, suprasti besikeičiančią darbo rinką ir priimti labiau pagrįstus sprendimus dėl mokymosi bei karjeros.",project_year:"2025",programme:"Erasmus+ KA152",project_code:"2025-1-LT02-KA152-YOU-000305967"},
 "digitalize":{title_lt:"Digitalize",summary_lt:"Skaitmeninių kompetencijų stiprinimas jaunimo darbuotojams.",description_lt:"Tarptautiniai mokymai jaunimo darbuotojams apie skaitmeninius metodus, bendradarbiavimą ir prasmingą technologijų taikymą neformaliajame ugdyme.",project_year:"2021",programme:"Erasmus+ KA153",project_code:"2021-1-LT02-KA153-YOU-000020814"},
 "environmental-pollution":{title_lt:"Control Guide Against Environmental Pollution",summary_lt:"Aplinkosauga, europinės vertybės ir jaunimo bendradarbiavimas.",description_lt:"Jaunimo mainai, skirti aplinkosauginiam sąmoningumui, aktyviam pilietiškumui ir bendroms Europos vertybėms stiprinti.",project_year:"2021",programme:"Erasmus+ KA152",project_code:"2021-2-CZ01-KA152-YOU-000038377"},
 "karjeros-kompasas":{title_lt:"Karjeros kompasas: kaip rinktis nežinomybės laikais",excerpt_lt:"Penki klausimai, padedantys jaunuoliui sprendimą paversti kryptimi.",content_lt:"## Karjera nėra vienas teisingas atsakymas\n\nGeras karjeros sprendimas prasideda ne nuo profesijų sąrašo, o nuo savęs pažinimo. Ką mėgstu daryti? Kokias problemas noriu spręsti? Kokioje aplinkoje geriausiai mokausi?\n\n## Penki klausimai sau\n\n1. Kas mane natūraliai įtraukia?\n2. Kokius gebėjimus norėčiau stiprinti?\n3. Kokią vertę noriu kurti kitiems?\n4. Kokių patirčių dar neturiu?\n5. Koks mažas eksperimentas padėtų pasitikrinti kryptį?\n\nKarjeros planas neturi būti akmenyje iškaltas maršrutas. Jis gali būti kompasas, padedantis pasirinkti kitą prasmingą žingsnį."},
 "skaitmeninis-pasitikejimas":{title_lt:"Skaitmeninis pasitikėjimas yra daugiau nei įgūdžiai",excerpt_lt:"Kodėl technologinis raštingumas prasideda nuo smalsumo, o ne nuo programos.",content_lt:"## Įrankis keičiasi, gebėjimas lieka\n\nSkaitmeninis pasitikėjimas reiškia drąsą tyrinėti, kritiškai vertinti informaciją ir sąmoningai pasirinkti tinkamą priemonę. Svarbu ne tik mokėti paspausti mygtuką, bet suprasti, kokią problemą juo sprendžiame.\n\nMokymuose skatiname mažus praktinius eksperimentus, bendradarbiavimą ir refleksiją. Taip technologijos tampa ne kliūtimi, o kūrybos erdve."},
 "judejimas-visiems":{title_lt:"Judėjimas visiems: kaip veiklą padaryti įtraukią",excerpt_lt:"Praktiniai principai planuojant sportą skirtingų fizinių gebėjimų grupei.",content_lt:"## Pirmiausia – žmogus, ne apribojimas\n\nĮtrauki veikla prasideda nuo atviro pokalbio apie poreikius, alternatyvių būdų dalyvauti ir aplinkos pritaikymo. Tas pats tikslas gali turėti kelis skirtingus kelius.\n\nSvarbiausia kurti atmosferą, kurioje pagalbos paprašyti saugu, o skirtingas tempas nėra vertinamas kaip trūkumas."}
};
export default function ContentDetail({kind}:{kind:Kind}){const {slug}=useParams<{slug:string}>();const [item,setItem]=useState<Row|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{if(!slug)return;supabase.from(kind).select("*").eq("slug",slug).eq("status","published").single().then(({data})=>{setItem((data as Row)||fallback[slug]||null);setLoading(false)})},[kind,slug]);if(loading)return <main className="content-state">Kraunama…</main>;if(!item)return <main className="content-state"><h1>Įrašas nerastas</h1><a href={kind==="projects"?"/projektai":"/straipsniai"}>← Grįžti</a></main>;const project=kind==="projects";const title=String(item.title_lt||"");const intro=String(item[project?"summary_lt":"excerpt_lt"]||"");const body=String(item[project?"description_lt":"content_lt"]||"");return <main className="inner-page"><PublicHeader/><article className="detail-new"><a className="back-link" href={project?"/projektai":"/straipsniai"}>← {project?"Visi projektai":"Visi straipsniai"}</a><header><span>{project?String(item.programme||"PROJEKTAS"):"CONSUST ĮŽVALGOS"}</span><h1>{title}</h1><p>{intro}</p>{project&&<div className="detail-facts"><div><small>METAI</small><strong>{item.project_year}</strong></div><div><small>PROJEKTAS</small><strong>{item.project_code}</strong></div></div>}</header>{item.image_url&&<figure className="detail-cover"><img src={item.image_url} alt={`${title} projekto iliustracija`}/></figure>}<section className="detail-body"><aside><i>✦</i><span>{project?"MOKOMĖS · KURIAME · VEIKIAME":"ŽINIOS · PATIRTIS · KRYPTIS"}</span></aside><div><MarkdownContent text={body}/></div></section><section className="detail-cta"><h2>Turite idėją bendram projektui?</h2><a href="/kontaktai">Susisiekime ↗</a></section></article><PublicFooter/></main>}
