"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {supabase} from "../lib/supabase";
import MarkdownContent from "./MarkdownContent";
import PublicHeader from "./PublicHeader";
import PublicFooter from "./PublicFooter";
import useLanguage from "../lib/useLanguage";
type Kind="articles"|"projects";type Row=Record<string,string|null>;
export default function ContentDetail({kind}:{kind:Kind}){const lang=useLanguage();const english=lang==="en";const {slug}=useParams<{slug:string}>();const [item,setItem]=useState<Row|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);useEffect(()=>{if(!slug)return;let active=true;setLoading(true);setError(false);setItem(null);Promise.resolve(supabase.from(kind).select("*").eq("slug",slug).eq("status","published").maybeSingle()).then(({data,error})=>{if(!active)return;setError(Boolean(error));setItem(error?null:data as Row|null);setLoading(false)}).catch(()=>{if(active){setError(true);setLoading(false)}});return()=>{active=false}},[kind,slug]);if(loading||error||!item)return <main className="inner-page"><PublicHeader/><section className="catalog-list" aria-live="polite">{loading?<p>{english?"Loading…":"Kraunama…"}</p>:<><h1>{error?(english?"Unable to load content":"Nepavyko įkelti turinio"):(english?"Content not found":"Įrašas nerastas")}</h1>{error&&<p>{english?"Please try again later.":"Bandykite dar kartą vėliau."}</p>}<a href={kind==="projects"?"/projektai":"/straipsniai"}>← {english?"Back to the list":"Grįžti į sąrašą"}</a></>}</section><PublicFooter/></main>;const project=kind==="projects";const title=String(item[`title_${lang}`]||item.title_lt||"");const intro=String(item[`${project?"summary":"excerpt"}_${lang}`]||item[project?"summary_lt":"excerpt_lt"]||"");const body=String(item[`${project?"description":"content"}_${lang}`]||item[project?"description_lt":"content_lt"]||"");return <main className="inner-page"><PublicHeader/><article className="detail-new"><a className="back-link" href={project?"/projektai":"/straipsniai"}>← {project?(english?"All projects":"Visi projektai"):(english?"All articles":"Visi straipsniai")}</a><header><span>{project?String(item.programme||"PROJEKTAS"):"CONSUST ĮŽVALGOS"}</span><h1>{title}</h1><p>{intro}</p>{project&&<div className="detail-facts">{item.project_year&&<div><small>{english?"YEAR":"METAI"}</small><strong>{item.project_year}</strong></div>}{item.project_code&&<div><small>{english?"PROJECT":"PROJEKTAS"}</small><strong>{item.project_code}</strong></div>}</div>}</header>{item.image_url&&<figure className="detail-cover"><img src={item.image_url} alt={`${title} projekto iliustracija`}/></figure>}<section className="detail-body"><aside><i>✦</i><span>{project?(english?"LEARN · CREATE · ACT":"MOKOMĖS · KURIAME · VEIKIAME"):(english?"KNOWLEDGE · EXPERIENCE · DIRECTION":"ŽINIOS · PATIRTIS · KRYPTIS")}</span></aside><div><MarkdownContent text={body}/></div></section><section className="detail-cta"><h2>{english?"Have an idea for a joint project?":"Turite idėją bendram projektui?"}</h2><a href="/kontaktai">{english?"Get in touch ↗":"Susisiekime ↗"}</a></section></article><PublicFooter/></main>}
