import PublicHeader from "../../components/PublicHeader";
import PublicFooter from "../../components/PublicFooter";

const people=[
  ["MS","Mindaugas Samuolaitis","Direktorius","Daugiau nei 10 metų jaunimo karjeros planavimo ir valdymo patirties. Dalyvavo daugiau nei 20 nacionalinių ir tarptautinių projektų."],
  ["AA","Audronė Alijošiūtė-Paulauskienė","Tvarumo ekspertė","Daugiau nei 20 metų tvarumo strategijų ir gebėjimų stiprinimo patirties, apimančios daugiau nei 60 iniciatyvų."],
  ["DG","Deimantas Gaidamavičius","IT ir projektų vadovas","Technologijų, administravimo ir Erasmus+ projektų koordinavimo patirtis tarptautinėse komandose."],
  ["BS","Birutė Statkevičienė","Įtraukaus sporto ekspertė","Mokslininkė, trenerė ir plaukimo specialistė, dirbanti su regos bei kitų fizinių negalių turinčiais žmonėmis."],
  ["MS","Marija Stravinskaitė","Projektų koordinatorė","Karjeros, lyderystės, emocinio intelekto ir mišrių fizinių gebėjimų veiklų patirtis Erasmus+ projektuose."],
];
export default function AboutPage(){return <main className="inner-page"><PublicHeader/><section className="inner-hero about-inner"><div><span>01 / APIE MUS</span><h1>Patirtis, kuri tampa <em>galimybėmis.</em></h1></div><p>VšĮ „Alternatyvūs sprendimai tvariai ateičiai“ – Kaune veikianti nevyriausybinė organizacija, nuo 2014 metų jungianti jaunimą, švietimą, verslą, tvarumą ir įtraukų judėjimą.</p><div className="inner-route"><i/><i/><i/></div></section><section className="story-grid"><div className="story-label">MŪSŲ ISTORIJA</div><div><h2>Pokyčiui reikia ne tik idėjos. Jam reikia žmonių, žinių ir erdvės veikti.</h2><p>Padedame moksleiviams ir studentams integruotis į besikeičiančią darbo rinką, stipriname jaunimo darbuotojų skaitmenines kompetencijas ir tvarumo principus perkeliame į realią organizacijų bei bendruomenių veiklą.</p><p>Ypatingą dėmesį skiriame žmonių su fizine negalia įtraukčiai. Sportas, žygiai, plaukimas ir pritaikytos veiklos mums yra būdas mažinti socialinius barjerus ir kurti bendrystę.</p></div></section><section className="about-numbers"><article><strong>2014</strong><span>organizacijos pradžia</span></article><article><strong>20+</strong><span>projektų patirtis</span></article><article><strong>60+</strong><span>tvarumo iniciatyvų</span></article><article><strong>EU</strong><span>tarptautinis tinklas</span></article></section><section className="people-section"><div className="inner-title"><span>EKSPERTŲ TINKLAS</span><h2>Žmonės už CONSUST krypties.</h2></div><div className="people-full">{people.map((p,i)=><article key={p[1]}><div className={`portrait tone${i}`}><span>{p[0]}</span><i>0{i+1}</i></div><small>{p[2]}</small><h3>{p[1]}</h3><p>{p[3]}</p></article>)}</div></section><section className="partner-band"><span>ASOCIJUOTAS PARTNERIS</span><h2>Kauno kolegija</h2><a href="https://www.kaunokolegija.lt/en/" target="_blank" rel="noreferrer">Aplankyti partnerį ↗</a></section><PublicFooter/></main>}
